version: '3.8'

services:
  frontend-next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://kosa-backend-315281980252.asia-northeast3.run.app
      - NEXT_PUBLIC_WS_URL=wss://kosa-backend-315281980252.asia-northeast3.run.app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kosa-network

networks:
  kosa-network:
    driver: bridge
